[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/eta-checker/*"
  to = "https://quiet-jelly-feeb71.netlify.app/eta-checker/:splat"
  status = 200
  force = true